-- AlterTable
ALTER TABLE "Events" ALTER COLUMN "fromDate" DROP NOT NULL,
ALTER COLUMN "toDate" DROP NOT NULL,
ALTER COLUMN "bands" SET DEFAULT ARRAY[]::TEXT[],
ALTER COLUMN "website" DROP NOT NULL,
ALTER COLUMN "city" DROP NOT NULL,
ALTER COLUMN "country" DROP NOT NULL,
ALTER COLUMN "bandIds" SET DEFAULT ARRAY[]::TEXT[],
ALTER COLUMN "imageUrl" DROP NOT NULL;
